title: Portfolio - Maxime Carlier
firstname: Maxime
lastname: Carlier
email: 28m06c02@gmail.com
phone: "07 84 17 26 58"
country: France
education_level: "Master"
education_full: "Master ILJ (Ing√©nierie Logicielle pour les Jeux)"
profession: Game Developer
baseurl: ""
url: "https://carlier-maxime.github.io/"
repository: "https://github.com/Carlier-Maxime/Carlier-Maxime.github.io"

start_year: 2023
birth_date: 2002-06-28

social:
  github: Carlier-Maxime
  linkedin: maxime-carlier-6b9840226
  itch: metouais

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - .idea/
  - .github/

collections:
  projects:
    output: true

mediaDir: /assets/media/
videoDir: /assets/media/videos/
posterDir: /assets/media/posters/